server:
  tomcat:
    max-threads: 200 # tomcat最大线程数，默认为200
    uri-encoding: UTF-8  #url编码方式
    accesslog:
      enabled: true # 打开Tomcat的Access日志
      pattern: 'common' #设置日志格式默认common
      file-date-format: ".yyyy-MM-dd"
  #      directory: 'logs' # 日志文件目录
  port: 80
  servlet:
    session:
      timeout: 30m
    context-path: /
  #-------------------------------log 日志----------------------
logging:
  config: 'classpath:logback-spring.xml'
platform:
  logsPath: "./logs" #定义日志存储的路径
  uploadDir: "./data/uploadFile"
spring:
  datasource:
    url: 'jdbc:mysql://dev-mysql:3306/vip-hoody-site?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true'
    username: 'root'
    password: 'hoody'
#解决Swagger-UI 请求地址生成的问题，需要指向Nginx代理后的地址
springfox:
  documentation:
    swagger:
      v2:
        host: api/api