server:
  tomcat:
    max-threads: 200 # tomcat最大线程数，默认为200
    uri-encoding: UTF-8  #url编码方式
    accesslog:
      enabled: true # 打开Tomcat的Access日志
      pattern: 'common' #设置日志格式默认common
      file-date-format: ".yyyy-MM-dd"
  #      directory: 'logs' # 日志文件目录
  port: 8080
  servlet:
    session:
      timeout: 30m
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,text/html,application/xml
    min-response-size: 20KB
  #-------------------------------log 日志----------------------
logging:
  config: 'classpath:logback-spring.xml'
platform:
  logsPath: "./Springboot-server/logs" #定义日志存储的路径
  uploadDir: "./Springboot-server/storage"
  #静态文件地址,用于dev模式,通过Springboot映射静态资源,prod 模式 通过Nginx处理静态资源,最后需要 /
  staticPath: "G:/GitHub-workspace/vip-hoody-site/Springboot-server/storage/"
  aliyun:
    regionld: 'cn-hangzhou'
    access-key: '**********'
    access-key-secret: '**************'
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/vip-hoody-site?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true'
    username: 'root'
    password: 'abcAbc123'
