server:
  tomcat:
    max-threads: 200 # tomcat最大线程数，默认为200
    uri-encoding: UTF-8  #url编码方式
    accesslog:
      enabled: true # 打开Tomcat的Access日志
      pattern: 'common' #设置日志格式默认common
      file-date-format: ".yyyy-MM-dd"
  #      directory: 'logs' # 日志文件目录
  port: 80
  servlet:
    session:
      timeout: 30m
    context-path: /
spring:
  datasource:
    url: 'jdbc:mysql://dev-mysql:3306/vip-hoody-site?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true'
    username: 'root'
    password: 'hoodydb'

#解决SwaggerUI 执行测试的问题，不过访问v2/api-doc 是通过nginx强制重定向完成的
springfox:
  documentation:
    swagger:
      v2:
        host: 'yourURL/api'
  #-------------------------------log 日志----------------------
logging:
  config: 'classpath:logback-spring.xml'
platform:
  logsPath: "./logs" #定义日志存储的路 1径
  uploadDir: "./storage"
  #静态文件地址,用于dev模式,通过Springboot映射静态资源,prod 模式 通过Nginx处理静态资源,最后需要 /
  staticPath: "/hoody-site/storage/"
  aliyun:
    regionld: 'cn-hangzhou'
    access-key: '********'
    access-key-secret: '********'